### ISSUE TITLE
OPCUAAdapter.dll

### ISSUE THREAD

**Issue by moehmoeh** [Pinkisagit/OpenHistorian-OPC-UA-Adapter#1]
I Try to cofigure open historian using this adapter, but not work, then i realized that OPCUAAdapter.dll is not found. Where i can download the OPCUAAdapter.dll ?

**Comment by Pinkisagit** [comment]
You'll have to compile the source code (Step #1), to get the DLL file.

**Comment by moehmoeh** [comment]
Ok i already have dll file, thx.
